# Generated by Django 6.0.8 on 2026-09-26 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0002_vkuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='vkuser',
            name='notifications_enabled',
            field=models.BooleanField(default=True, verbose_name='Уведомления включены'),
        ),
        migrations.CreateModel(
            name='ScheduleChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(blank=True, default='', help_text='Пусто — все классы школы', max_length=10, verbose_name='Класс')),
                ('day', models.CharField(max_length=20, verbose_name='День недели')),
                ('change_type', models.CharField(choices=[('created', 'Добавлено'), ('updated', 'Изменено'), ('deleted', 'Удалено')], default='updated', max_length=20, verbose_name='Тип изменения')),
                ('notified', models.BooleanField(default=False, verbose_name='Уведомление отправлено')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='schedule_app.school', verbose_name='Школа')),
            ],
            options={
                'verbose_name': 'Изменение расписания',
                'verbose_name_plural': 'Изменения расписания',
                'ordering': ['-created_at'],
            },
        ),
    ]
