# Generated by Django 6.0.8 on 2026-09-26 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0003_vkuser_notifications_enabled_schedulechange'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Например: 12, 24, Спортзал, Бассейн', max_length=50, unique=True, verbose_name='Номер/название кабинета')),
                ('room_type', models.CharField(blank=True, choices=[('', 'Обычный'), ('п', 'Практика'), ('э', 'Экзамен'), ('б', 'Базовый'), ('спорт', 'Спортзал'), ('бассейн', 'Бассейн')], default='', max_length=20, verbose_name='Тип кабинета')),
                ('building', models.CharField(blank=True, max_length=100, verbose_name='Корпус/здание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Кабинет',
                'verbose_name_plural': 'Кабинеты',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название предмета')),
                ('short_name', models.CharField(blank=True, help_text='Например: МАТЕМ, РУСС ЯЗ, ФИЗ-РА', max_length=50, verbose_name='Сокращение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
                'ordering': ['name'],
            },
        ),
    ]
