# Generated by Django 6.0.8 on 2026-09-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0004_classroom_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='vkuser',
            name='show_bell_times',
            field=models.BooleanField(default=True, verbose_name='Показывать расписание звонков'),
        ),
        migrations.AddField(
            model_name='vkuser',
            name='strike_past_lessons',
            field=models.BooleanField(default=True, verbose_name='Зачёркивать прошедшие уроки'),
        ),
    ]
